name: Build resume image

on:
    workflow_dispatch:
        inputs:
            image_tag:
                description: 'Image tag'
                default: 'luke-code-works/resume:latest'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            IMAGE_TAG: ${{ inputs.image_tag }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install packages
              run: npm ci

            - name: Build
              run: npx nx run @luke-code-works/ng-apps-resume:build:production

            - name: Set up buildx
              uses: docker/setup-buildx-action@v3

            - name: Build image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: apps/ng-apps-resume/.docker/dockerfile
                  tags: ${{ env.IMAGE_TAG }}
                  no-cache: true
                  load: true

            - name: Save docker image
              run: docker save "${{ env.IMAGE_TAG }}" | gzip > resume.tar.gz

            - name: Upload docker image as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: resume
                  path: resume.tar.gz
